#!/usr/bin/env python

import ftools
import resource
import optparse
import sys
import os
import stat


def matrix_to_string(matrix, header):
    """
Note: this function is from: http://mybravenewworld.wordpress.com/2010/09/19/print-tabular-data-nicely-using-python/
i modified it a bit. ;-)

 Return a pretty, aligned string representation
 of a nxm matrix.
 
 This representation can be used to print any
 tabular data, such as database results. It
 works by scanning the lengths of each element
 in each column, and determining the format
 string dynamically.
 
 @param matrix: Matrix representation (list with n rows
  of m elements).
 @param header: Optional tuple with header elements to be
  displayed.
    """
    lengths = []
    matrix = [header] + matrix
    for row in matrix:
        for column in row:
            i = row.index(column)
            cl = len(str(column))
            try:
                ml = lengths[i]
                if cl > ml:
                    lengths[i] = cl
            except IndexError:
                lengths.append(cl)
 
    lengths = tuple(lengths)
    format_string = ""
    for length in lengths:
        format_string += "%-" + str(length) + "s    "
    format_string += "\n"
 
    matrix_str = ""
    #matrix_str += format_string % header
    for row in matrix:
        matrix_str += format_string % tuple(row)
 
    return matrix_str



def main():
    parser = optparse.OptionParser(description="Determine how much of a file is in filesystem page-cache.")

    parser.add_option('-d', '--directory', dest='directory', default=None,
                      help="Recursively descend into a directory")

    options, args = parser.parse_args()

    if len(args) == 0 and options.directory == None:
        parser.print_help()
        return 1

    page_size = resource.getpagesize()
    header = ['filename', 'file size', 'total pages', 'pages cached', 'cached size', 'percentage cached']
    rows = []

    if options.directory:
        for (path, dirs, files) in os.walk(options.directory):
            for myfile in files:
                f = os.path.join(path,myfile)
                fd = file(f,'r')
                pages_cached, pages_total = ftools.fincore_ratio(fd.fileno())
                file_size = os.fstat(fd.fileno())[stat.ST_SIZE]
                fd.close()
                rows.append([f, file_size, pages_total, pages_cached, (pages_cached * page_size), (float(pages_cached) / float(pages_total)) * 100.0])

    for f in args:
        fd = file(f, 'r')
        pages_cached, pages_total = ftools.fincore_ratio(fd.fileno())
        file_size = os.fstat(fd.fileno())[stat.ST_SIZE]
        fd.close()
        rows.append([f, file_size, pages_total, pages_cached, (pages_cached * page_size), (float(pages_cached) / float(pages_total)) * 100.0])

    result = matrix_to_string(rows, header)
    print result


if __name__ == '__main__':
    main()
