#!/usr/bin/env python

# Copyright 2010 Tailrank, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
# License for the specific language governing permissions and limitations under
# the License.
#
# author: David Stainton
#

__author__ = "David Stainton"
__copyright__ = "Copyright 2010 Tailrank, Inc."
__license__ = "Apache License"

import os
import sys
import time
import stat
import math

def resolve ( value, resolution ):
    return int( math.floor( float(value)/resolution ) * resolution )

def main():

    # must create if it doesn't exist
    log_dir = '/var/spool/filestats'

    day_secs = 24 * 60 * 60

    #if len(sys.argv) != 2:
    #    print "usage: %s <directory>" % sys.argv[0]
    #    return 1

    mydir = '/var/lib/mysql/blogindex'
    files = os.listdir(mydir)

    now = time.time()
    segment_time = resolve(now, day_secs)
 
    for f in files:
        pathname = os.path.join(mydir, f)
        statinfo = os.stat(pathname)
        # if it's a regular file
        if stat.S_ISREG(statinfo[stat.ST_MODE]):
            report_dir = os.path.join(log_dir, f)
            if not os.path.exists(report_dir):
                os.mkdir(report_dir)
            filename = "%s.log" % segment_time
            file_path = os.path.join(report_dir, filename)
            fh = open(file_path, 'a')
            fh.write("%s %s\n" % (int(now), statinfo.st_size))
            fh.close()

if __name__ == '__main__':
    sys.exit(main())

